# Generated by Django 3.2.8 on 2022-06-29 10:56
import uuid

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.db.migrations import RunPython
from rest_framework.utils import json


def initial_data(apps, schema_editor):
    account_model = apps.get_model('api_accounts', 'Account')
    json_data = json.load(open('api_accounts/constants/account.json'), encoding='utf8')
    accounts = []
    for account_data in json_data:
        account = account_model(id=uuid.uuid4(),
                                username=account_data.get('username'),
                                password=make_password(account_data.get('password')))
        accounts.append(account)
    account_model.objects.bulk_create(accounts)


class Migration(migrations.Migration):
    dependencies = [
        ('api_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_data, RunPython.noop)
    ]
