# Generated by Django 3.2.8 on 2022-06-29 10:56
import os
import uuid

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.db.migrations import RunPython
from rest_framework.utils import json

from api_accounts.constants import RoleData


def initial_data(apps, schema_editor):
    account_model = apps.get_model('api_accounts', 'Account')
    json_data = json.load(open('api_accounts/constants/admin.json'))
    admin_role = RoleData.ADMIN.value.get('id')
    default_admin_password = os.getenv('DEFAULT_ADMIN_PASSWORD')
    accounts = []
    for account_data in json_data:
        account = account_model(id=uuid.uuid4(),
                                username=account_data.get('username'),
                                password=make_password(default_admin_password),
                                role_id=admin_role)
        accounts.append(account)
    account_model.objects.bulk_create(accounts)


class Migration(migrations.Migration):
    dependencies = [
        ('api_accounts', '0003_migrate_role_data'),
    ]

    operations = [
        migrations.RunPython(initial_data, RunPython.noop)
    ]
